[platformio]
src_dir = main

; [env:adafruit_qualia_s3_rgb666]
; platform = espressif32
; board = adafruit_qualia_s3_rgb666
; framework = arduino
; upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem101
; ; Native USB - board handles USB mode, no flags needed here
; build_flags = -DARDUINO_USB_MODE=1
; monitor_speed = 115200
; board_build.partitions = partitions.csv
; lib_deps =
;     ;adafruit/Adafruit TinyUSB Library @ ^3.1.4
;     h2zero/NimBLE-Arduino @ ^1.4.2

[env:ble]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 460800
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit TinyUSB Library @ ^3.1.4
    h2zero/NimBLE-Arduino @ ^1.4.2