[platformio]
src_dir = main

[env:adafruit_qualia_s3_rgb666]
platform = espressif32
board = adafruit_qualia_s3_rgb666
framework = arduino

; TODO COMMENT/UNCOMMENT FOR USER MODE
board_build.usb_mode = USB_OTG

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1
    -DCFG_TUD_HID=1

; TODO UNCOMMENT FOR DEBUGGING
; board_build.usb_mode = CDC
; build_flags =
;     -DARDUINO_USB_CDC_ON_BOOT=1
;     -DCFG_TUD_HID=1

; Native USB - board handles USB mode, no flags needed here

monitor_speed = 115200
board_build.partitions = partitions.csv

lib_deps =
    ;adafruit/Adafruit TinyUSB Library @ ^3.1.4
    h2zero/NimBLE-Arduino @ ^1.4.2
